### PR TITLE
Pythonic unit test module

### PR DESCRIPTION
**Pull request by jpventura**
- Create a `tests` module and add `__init__.py` file
  - Rename `solution_test.py` to `tests/test_solution.py`
  - Run tests calling `python -m unittest`

### CODE REVIEW

**Comment by jpventura** [comment]
@luisguiserrano Any updates on this? :-)

**Review by cgearhart — CHANGES_REQUESTED** [review]
There are too many changes unrelated to the purpose of the PR.

- Renaming function parameters isn't essential
- gitignore changes are not essential
- README update is not essential except for the update to test instructions (although I would let _this one_ slide)

Break up the PR into an atomic commit and I'll merge. If you'd like to refactor the sudoku code or update the gitignore, submit those separately (although it would be better to open an enhancement issue first so that we can discuss and scope any required support elsewhere).

**Comment by jpventura** [comment]
@cgearhart **done!**. This PR contains only the **unit test modifications**.

I will open the following issues:

  - Update `.gitignore` list of files.
  - Improve `README.md` formatting.
  - Improve pydoc at initial solution file.

**Comment by jpventura** [comment]
@cgearhart any updates on this?

**Comment by jpventura** [comment]
@cgearhart any updates on this?

**Comment by cgearhart** [comment]
Sorry -- I'm reviewing the new PR now.

**Pull request closed without merging**
